version: '3.7'

services:

  application:
    build: .
    restart: always
    ports:
      - 8888:8888
    links:
        - mongodb:database

  mongodb:
    image: mongo:5.0.15
    ports:
      - 27017:27017
